- name: Aanmaken directory
  ansible.builtin.file:
    path: /backup
    state: directory
    owner: bart
    group: bart
    mode: u+rwx,g=r,o-rwx
  become: yes
  become_user: root
  become_method: sudo