- name: Installeer de python bibliotheek shutil
  ansible.builtin.pip:
    name: shutil
- name: Voer het python script uit script2.py
  ansible.builtin.script: /home/bart/script2.py
  args:
    executable: python3