---
- hosts: all
  become: true
  pre_tasks:
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: script/script1.py
      dest: /home/bart/script1.py
      owner: bart
      group: bart
      mode: '0755'
  - name: Another symbolic mode example, adding some permissions and removing others
    ansible.builtin.copy:
      src: script/script2.py
      dest: /home/bart/script2.py
      mode: u+rwx,g-x,o-x

  tasks:
  - include_tasks: taken/play_script.yml
  - include_tasks: taken/play_script.yml
  
  

