---
- hosts: all
  become: true
  tasks:
  - name: Copy file with owner and permissions
    ansible.builtin.copy:
      src: script1.py
      dest: /home/bart/script1.py
      owner: bart
      group: bart
      mode: '0644'

  - name: Another symbolic mode example, adding some permissions and removing others
    ansible.builtin.copy:
      src: script2.py
      dest: /home/bart/script2.py
      mode: u+rw,g-wx,o-rwx

  - name: Run a script using an executable in a system path
    ansible.builtin.script: /script1.py
    args:
      executable: python3

  - name: Install bottle python package
    ansible.builtin.pip:
      name: shutil

  - name: Run a script using an executable in a system path
    ansible.builtin.script: /script2.py
    args:
      executable: python3