---
- hosts: all
  become: true
  pre_tasks:
  - name: Kopieer script1.py bestand en stel de rechten in
    ansible.builtin.copy:
      src: script/script1.py
      dest: /home/bart/script1.py
      owner: bart
      group: bart
      mode: '0755'
  - name: Kopieer script2.py bestand en stel de rechten in
    ansible.builtin.copy:
      src: script/script2.py
      dest: /home/bart/script2.py
      mode: u+rwx,g-x,o-x

  tasks:
  - include_tasks: taken/play_script1.yml
  - include_tasks: taken/play_script2.yml
  
  

