---
- hosts: all
  become: true
  tasks:
  - name: Install ntpdate
    ansible.builtin.package:
      name: ntpdate
      state: present

  # This uses a variable as this changes per distribution.
  - name: Remove the apache package
    ansible.builtin.package:
      name: "{{ apache }}"
      state: absent

  - name: Install the latest version of Apache and MariaDB
    ansible.builtin.package:
      name:
        - nmap
        - inetutils-ping
        - iputils
        - iftop
        - hping3
        - ptunnel
        - tcpdump
        - whatweb
        - nikto
        - gobuster
        - seclists   # woordlijsten
        - sublist3r
        - amass
        - git
        - tshark
        - timeout
        - tmux
        - netcat-traditional
        state: latest
  - name: Reboot machine and send a message
    ansible.builtin.reboot:
      msg: "Rebooting machine in 5 seconds"