---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  pre_tasks:

  - name: installeer updates op een RedHat Server
    tags: always
    ansible.builtin.dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"

  - name: installeer updates op een Ubuntu Server
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  tasks:
  
  - name: Installatie van nmap
    ansible.builtin.package:
      name:
        - nmap