---
- name: Update servers
  hosts: tmservers
  remote_user: bart
  tasks:
  - name: Ping all de VM's
    ping:
  - name: backup passwd en group
    copy:
      src: /etc/passwd 
      dest: /etc/passwd.bak
      owner: root
      group: root
      mode: 0644
  - name: backup group
    copy:
      src: /etc/group
      dest: /etc/group.bak
      owner: root
      group: root
      mode: 0644