---
- hosts: all
  gather_facts: no
  tasks:
    - name: Copy file to remote host
      copy:
        src: test.txt
        dest: /home/bart/bestandje.txt
        owner: bart
        group: bart
        mode: '644'  
    - name: Run command on remote host
      shell: ls -la /etc/
